# Generated by Django 3.0.2 on 2020-03-22 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='type',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='url',
        ),
    ]
